### PR TITLE
portfolio: Accessibility

### PR DESCRIPTION
**Pull request by joffreynk**
### portfolio: Accessibility changes
**changes fixed**
- page title fixed
- images alternatives fixed 
- text heading orders fixed

**The following list was ok**

- color contrast was ok
- Resizing was ok
- moving content was not required in the implementation
- multimedia was ok
- the basic structure of the page was ok

### CODE REVIEW

**Review by mahbubul14 — CHANGES_REQUESTED** [review]
Hi @JoffreyNK ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Kindly add your evaluation report to the description of your pull request. You can check the project requirements as well.

requirements

- [ ] In your `README` file, Kindly update the getting started section. This should be an example of how you may give instructions on setting up your project locally.

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Github flow used properly.
:heavy_check_mark: Well implemented Figma design.

### Optional suggestions

- [ ] The commit message should be written in the imperative tense and the first letter also should be capitalized. `Ex: "Fix bug" instead of "fix bug".` [For more details.](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by joffreynk** [comment]
I have added the changes I made in PR, do I have to add to show title no issues when I have fixed it?

**Comment by mahbubul14** [comment]
> I have added the changes I made in PR, do I have to add to show title no issues when I have fixed it?

Hi @JoffreyNK, 

`Page titles - no issues found` is an example. It would be better if you have added it to all checklists.

**Note: Please, remember to tag me in your question so I can receive the notification.**

**Review by ShahierNashaat — APPROVED** [review]
Hi @JoffreyNK , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
